#设置启动端口
server:
  port: 8080

spring:
  #配置数据源
  datasource:
    # MySQL 5.x及以前版本,驱动配置driverClassName是com.mysql.jdbc.Driver
    # 之后是 com.mysql.cj.jdbc.Driver
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot?useUnicode=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&characterEncoding=utf-8
    username: root
    password: root

#mybatis 配置文件配置
#mybatis:
  #注意: 一定要对应mapper映射xml文件的所在路径
  #mapper-locations: classpath*:**/sqlmap/*.xml
  #注意: 配置实体类别名  对应实体类的路径
  #type-aliases-package: com.example.demo.model
  #configuration:
    # 自动驼峰命名转换
    #mapUnderscoreToCamelCase: true

# mybatis 分页插件  pagehelper
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: coount=countSql
